#ifndef FREQUENCY_EXTRAPOLATION_OPERATING_MODES_H
#define FREQUENCY_EXTRAPOLATION_OPERATING_MODES_H

enum Frequency_extrapolation_operating_modes
{
	COMMON_USAGE,
	FILL_UP_FREQUENCY_EXTRAPOLATION_STORE,
	FILL_UP_FOR_PRELIMINARILY_SETTET_STRUCTURES,
	ANALYSE_CLUSTER_ONLY
};


#endif

